PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  ?Player_iri a dbo:SoccerPlayer;
    dbp:number ?number;
    dbp:birthPlace ?b_iri;
    dbp:position ?Position_iri;
}
FROM <file:table_2.csv> 
WHERE {
  BIND (xsd:integer(?No) AS ?number)
  BIND (IRI(?Player) AS ?Player_iri)
  BIND (IRI(?b) AS ?b_iri)
  BIND (IRI(?Position) as ?Position_iri)
}