PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ex:  <http://health.example.org/property#>

CONSTRUCT {
  ?s a dbo:Vaccine;
    ex:vaersID ?vID;
    ex:recvDate ?d;
    ex:age ?age
    ex:vaccine ?v;
    ex:totalVaccinations ?t;
}
FROM <file:D:/DBpedia2021/healthcare-platform/Data/kaggle_covidworldvaccinationprogress/country_vaccinations_by_manufacturer.csv>
WHERE {
  BIND (URI(CONCAT('http://dbpedia.org/resource/',?location,?vaccine)) AS ?s)
  BIND (xsd:date(?date) AS ?d)
  BIND (xsd:string(?vaccine) as ?v)
  BIND (xsd:integer(?total_vaccinations) as ?t)
}