apiVersion: batch/v1
kind: CronJob
metadata:
  name: healthcare
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: healthcare
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - date; echo Update data sets
          restartPolicy: OnFailure
