PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ex:  <http://health.example.org/property#>

CONSTRUCT {
  ?s a dbo:VaccinationStatistics;
    ex:vaersID ?vID;
    ex:vaxType ?vType;
    ex:vaxManu ?vManu;
    ex:vaxName ?vName;
}
WHERE {
  BIND (URI(CONCAT('http://dbpedia.org/resource/vaccine-symptoms/',?VAX_MANU)) AS ?s)
  BIND (xsd:integer(?VAERS_ID) as ?vID)
  BIND (xsd:string(?VAX_TYPE) AS ?vType)
  BIND (xsd:string(?VAX_MANU) AS ?vManu)
  BIND (xsd:string(?VAX_NAME) AS ?vName)
}