PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ex:  <http://health.example.org/property#>

CONSTRUCT {
  ?s a dbo:Vaccine;
    ex:vaersID ?vID;
    ex:recvDate ?d;
    ex:age ?age;
    ex:sex ?sex;
    ex:symptom ?symptom;
    ex:allergies ?allergies;
}
WHERE {
  BIND (URI(CONCAT('http://dbpedia.org/resource/vaccine-symptoms/age',?age)) AS ?s)
  BIND (xsd:integer(?vaers_id) as ?vID)
  BIND (xsd:date(?recvdate) AS ?d)
  BIND (xsd:integer(?age_yrs) as ?age)
  BIND (xsd:string(?sex) as ?sex)
  BIND (xsd:string(?symptom_text) as ?symptom)
  BIND (xsd:string(?allergies) as ?allergies)
}